### ISSUE TITLE
security 도 하나의 도메인이라 볼 수 있는데 core/common 디렉토리에 있는건 아니라고 생각하고 또 유저 인증에만 관련있기에 core에 있을 service가 아니라고 생각해요. 

### ISSUE THREAD

**Issue by songju7920** [Team-LoopCat/Helper_Backend#8]
security 도 하나의 도메인이라 볼 수 있는데 core/common 디렉토리에 있는건 아니라고 생각하고 또 유저 인증에만 관련있기에 core에 있을 service가 아니라고 생각해요. 그냥 infrastructure 에 그대로 냅두는게 맞지 않나요?

persistence 모듈에서 jwt토큰을 확인하는 것도 아니라서...
다른 모듈에서  core로 모아야지 core에서 흩어지는 방향으로 가면 안돼요

_Originally posted by @zios0707 in https://github.com/Team-LoopCat/Helper_Backend/pull/7#pullrequestreview-2374471649_

**Comment by songju7920** [comment]
그럼 해당 Service들을 infrastructure으로 이동시키고, 해당 service에 대한 Port를 만들라는 말씀이신가요?

**Comment by zios0707** [comment]
지금 core 에 있는 port와 service를 그대로 infrastructure 의 security 도메인으로 옮기시면 되지 않을까요
